# Generated by Django 4.1.2 on 2022-10-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0002_tag_rename_reated_project_created_project_vote_ratio_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to=""
            ),
        ),
    ]
